# Generated by Django 3.1.7 on 2022-08-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpperCase',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.profile',),
        ),
    ]
